twitter_handle: RailsConf
twitter_hashtag: RailsConf
instagram_client_id: e274913172cd4e75a81d3981159c6938
instagram_tag: RailsConf

sponsors:
  -
    name: Pivotal Labs
    logo: pivotallabs-logo.png
  -
    name: Definitely Not Pivotal Labs
    logo: pivotallabs-logo.png
