twitter_handle: RailsConf
twitter_hashtag: RailsConf
instagram_client_id: e274913172cd4e75a81d3981159c6938
instagram_tag: RailsConf

sponsors:
  -
    logo: pivotallabs-logo.png
  -
    logo: engine-yard-logo.png

events:
  -
    time: 2011-6-4 10:00:00 -0400 
    name: Meet and Greet
    speaker: 
  -
    time: 2011-6-4 11:00:00 -0400
    name: Introduction to Ruby
    speaker: Josh Knowles
  - 
    time: 2011-6-4 11:55:00 -0400
    name: Lunch break
    speaker: 
