twitter_handle: ladygaga
twitter_hashtag: ladygaga
instagram_client_id: e274913172cd4e75a81d3981159c6938
instagram_tag: ladygaga
foursquare_vendor_id: 41422
foursquare_oauth_token: VSKP32HTB1X1TX51ORO1LQVUOLNXR1OMTEFPCE3VM3RYFBN1

sponsors:
  -
    logo: pivotallabs-logo.png
  -
    logo: engine-yard-logo.png

events:
  -
    time: 2011-5-20 17:00:00 -0400 
    title: Meet and Greet
    speaker: 
  -
    time: 2011-6-4 11:00:00 -0400
    title: Introduction to Ruby
    speaker: Josh Knowles
  - 
    time: 2011-6-4 11:55:00 -0400
    title: Lunch break
    speaker: 
